[package]
name = "recloser"
version = "0.1.0"
authors = ["lerouxrgd <leroux.rgd@gmail.com>"]
edition = "2018"
description = "A concurrent circuit breaker implemented with ring buffers"
repository = "https://github.com/lerouxrgd/recloser"
license = "MIT"
readme = "README.md"

[dependencies]
crossbeam = "0.7"
futures = "0.1"

[dev-dependencies]
criterion = "0.2"
failsafe = "0.3"
fake_clock = "0.3"
matches = "0.1"
num_cpus = "1.10"
rand = "0.6"
rayon = "1.1"
tokio = "0.1"

[[bench]]
name = "recloser"
harness = false