[package]
name = "recloser"
version = "0.2.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "A concurrent circuit breaker implemented with ring buffers"
repository = "https://github.com/lerouxrgd/recloser"
license = "MIT"
readme = "README.md"

[dependencies]
crossbeam = "0.7"
pin-project = "0.4"

[dev-dependencies]
async-std = "1.0"
criterion = "0.3"
failsafe = "0.3"
fake_clock = "0.3"
futures = "0.3"
matches = "0.1"
num_cpus = "1.11"
rand = "0.7"
rayon = "1.2"

[[bench]]
name = "recloser"
harness = false