[package]
name = "recloser"
version = "0.1.0"
authors = ["lerouxrgd <leroux.rgd@gmail.com>"]
edition = "2018"
repository = "https://github.com/lerouxrgd/recloser"
license = "MIT"
readme = "README.md"

[dependencies]
crossbeam = "0.7"

[dev-dependencies]
fake_clock = "0.3"
matches = "0.1"
rand = "0.6"